### ISSUE TITLE
Program/IDE to view post-mortem crash

### ISSUE THREAD

**Issue by c1728p9** [adamgreen/CrashCatcher#1]
I was curious what program you use or would recommend using to view the crash?  Something like GDB or qemu?

**Comment by adamgreen** [comment]
CrashCatcher is meant to be used with [CrashDebug](https://github.com/adamgreen/CrashDebug).  It sort of acts like an emulator to load up the crash dump and then presents a socket to GDB.  GDB then thinks it is just connecting to a remote debug stub like openOCD or pyOCD.
