### ISSUE TITLE
The dump file failed to load RAM memory region with elf 

### ISSUE THREAD

**Issue by pronoy13cap** [adamgreen/CrashCatcher#16]
ERROR: The dump file failed to load RAM memory region at 0x2003068C - 0x2003063C. CrashDebug - Cortex-M Post-Mortem Debugging Aid (1.7-20210805.0) Copyright (C) 2021 Adam Green
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. Usage: CrashDebug (--elf elfFilename | --bin imageFilename baseAddress)
                   --dump dumpFilename
                  [--alias baseAddress size redirectAddress]
Where: NOTE: The --elf and --bin options are mutually exclusive.  Use one
             or the other but not both.
       --elf is used to provide the filename of the .elf image containing
         the device's FLASH contents at the time of the crash.
       --bin is used to provide the filename of the binary image loaded into
         the device's FLASH when the crash occurred. These binary images are
         typically generated by running:
           "arm-none-eabi-objcopy -O binary input.elf output.bin"
         The baseAddress parameter indicates where the contents of the .bin
         file was loaded into FLASH.  This address will typically be
         0x00000000 unless a boot loader was in use.
       --dump is used to provide the filename of the crash dump which
         contains the contents of RAM and the CPU registers at the time of
         the crash.  See the following link to learn more about generating
         these crash dumps:http://github.com/adamgreen/CrashDebug#crash-dump-generation
       --alias is used to trap memory accesses to the region defined
         by baseAddress/size and redirect them to the region at
         redirectAddress. For example acesses to baseAddress will access
         redirectAddress instead).
Encountered unexpected error: 18
Remote communication error.  Target disconnected.: No error.

Also the output of the command :- 
arm-none-eabi-objdump -h -p your_program.elf

LR_App.elf:     file format elf32-littlearm Program Header:
    LOAD off    0x00000034 vaddr 0x0c00c000 paddr 0x0c00c000 align 2**2
         filesz 0x00000234 memsz 0x00000234 flags r-x
    LOAD off    0x00000268 vaddr 0x0c00c800 paddr 0x0c00c800 align 2**2
         filesz 0x000197b8 memsz 0x000197b8 flags r-x
    LOAD off    0x00019a20 vaddr 0x0c028000 paddr 0x0c028000 align 2**5
         filesz 0x000001a0 memsz 0x000001a0 flags r-x
private flags = 0x5000000: [Version5 EABI] Sections:
Idx Name          Size      VMA       LMA       File off  Algn
  0 A0            00000234  0c00c000  0c00c000  00000034  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, CODE
  1 P1 ro         000197b8  0c00c800  0c00c800  00000268  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, CODE
  2 P2            000001a0  0c028000  0c028000  00019a20  2**5
                  CONTENTS, ALLOC, LOAD, READONLY, CODE
  3 P3 rw         00001684  30000000  30000000  00019bc0  2**2
                  ALLOC
  4 P3 zi         0001e994  30001684  30001684  00019bc0  2**2
                  ALLOC
  5 P3 ui         00004000  30020018  30020018  00019bc0  2**3
                  ALLOC
  6 P4 rw         00000024  30030000  30030000  00019bc0  2**2
                  ALLOC
  7 P4 zi         000007bc  30030024  30030024  00019bc0  2**2
                  ALLOC
  8 P5            00000868  30038000  30038000  00019bc0  2**2
                  ALLOC
  9 .debug_abbrev 00009346  00000000  00000000  00019bc0  2**0
                  CONTENTS, READONLY, DEBUGGING, OCTETS
10 .debug_aranges 000046c4  00000000  00000000  00022f08  2**0
                  CONTENTS, READONLY, DEBUGGING, OCTETS
11 .debug_frame  00009d91  00000000  00000000  000275cc  2**0
                  CONTENTS, READONLY, DEBUGGING, OCTETS
12 .debug_info   0009da2d  00000000  00000000  00031360  2**0
                  CONTENTS, READONLY, DEBUGGING, OCTETS
13 .debug_line   00095e12  00000000  00000000  000ced90  2**0
                  CONTENTS, READONLY, DEBUGGING, OCTETS
14 .debug_loc    00014afd  00000000  00000000  00164ba4  2**0
                  CONTENTS, READONLY, DEBUGGING, OCTETS
15 .debug_macinfo 0000c7d1  00000000  00000000  001796a4  2**0
                  CONTENTS, READONLY, DEBUGGING, OCTETS
16 .debug_pubnames 00006f18  00000000  00000000  00185e78  2**0
                  CONTENTS, READONLY, DEBUGGING, OCTETS
17 .debug_ranges 00005f68  00000000  00000000  0018cd90  2**0
                  CONTENTS, READONLY, DEBUGGING, OCTETS
18 .debug_types  00004cd4  00000000  00000000  00192cf8  2**0
                  CONTENTS, READONLY, DEBUGGING, OCTETS
19 .iar.debug_frame 0001675d  00000000  00000000  001979cc  2**0
                  CONTENTS, READONLY
20 .iar.debug_line 00030fbf  00000000  00000000  001ae12c  2**0
                  CONTENTS, READONLY
21 .comment      00071ed9  00000000  00000000  001df0ec  2**0
                  CONTENTS, READONLY
22 .iar.rtmodel  00000042  00000000  00000000  00250fc8  2**0
                  CONTENTS, READONLY
23 .ARM.attributes 0000002e  00000000  00000000  0025100c  2**0
                  CONTENTS, READONLY

**Comment by adamgreen** [comment]
```
ERROR: The dump file failed to load RAM memory region at 0x2003068C - 0x2003063C
```
It's weird that the starting address is a higher value than the ending address. Those addresses should be coming from the crash dump itself. Is it possible that the starting and ending addresses were incorrect when returned from `CrashCatcher_GetMemoryRegions()`?
