### ISSUE TITLE
Support for lpc 1833

### ISSUE THREAD

**Issue by RajaniSureja** [adamgreen/CrashCatcher#5]
I am using LPC 1833.
Is your CrashCatcher code is work with LPC 1833(ARM Cortex M3)?
because after use of your code my finding are:
"vmrs        r1, fpscr	\n"					
"vstmia.32   r0!, {s0 - s31}	\n"
these above instructions are not supported and give error like(selected processor does not support Thumb mode `vmrs r1,fpscr'). these instruction are useful for HexDump Routines.
so, how to use HexDump Routines?

**Comment by adamgreen** [comment]
@RajaniSureja 
Can you dump the 32-bit word at 0xE000ED88, the Coprocessor Access Control Register (CPACR). CrashCatcher should only attempt to execute those FPU instructions if it thinks that the FPU co-processors (CP10 & CP11) have been enabled. Dumping the CPACR will let us know if the LPC1833 is erroneously indicating that they are enabled when they aren't. I would like to rule that out first.

**Comment by adamgreen** [comment]
When you hit the hard fault in the HexDump routines, it would also be helpful to dump the contents of **g_pCrashCatcherCoprocessorAccessControlRegister** in addition to the CPACR.

**Comment by RajaniSureja** [comment]
@adamgreen Thanks, I got Hex dump. now can you help me what is next procedure with these dumps?
i am using windows 7 64 bit.

**Comment by adamgreen** [comment]
>Thanks, I got Hex dump.

Excellent! What did you need to do to get it to work?

>now can you help me what is next procedure with these dumps?

[The CrashDebug documentation](https://github.com/adamgreen/CrashDebug#readme) should contain everything you need to load these hex dumps up into arm-none-eabi-gdb.

**Comment by RajaniSureja** [comment]
@adamgreen 
After getting Hex dump i follow steps:
-> Copied Hex dump in .txt file and name it MainCrashDump.txt.
-> I am using Red Suite IDE in which it generate axf file. I change it from axf to elf in compiler setting.
-> After that i get main.elf.
-> Then i fire following command from command prompt:
     arm-none-eabi-gdb main.elf -ex "set target-charset ASCII" -ex "target remote | CrashDebug --elf main.elf --dump MainCrashDump.txt" 
-> I am getting error which i attached. PFA.
![capture](https://user-images.githubusercontent.com/25840668/34104381-327674fe-e416-11e7-912d-ab5803816e4d.PNG)
->is i am missing something?

**Comment by adamgreen** [comment]
It looks like it can't find CrashDebug. Make sure that it is in your PATH. 

You could also just try running ```CrashDebug --elf main.elf --dump MainCrashDump.txt``` from the console to make sure that it will start outside of GDB without error. If it is working, then you will see no error text and the console will appear to be hung (waiting for commands from GDB). CTRL+C to exit. Once you have it working that way, you can run it from within GDB command line.

**Comment by RajaniSureja** [comment]
@adamgreen 
Thanks....!! now its working fine...but still i need more information for variable store in RAM. I write the RAM starting and ending address in function CrashCatcher_GetMemoryRegions(). the size of RAM is 40k so,when dump start it crash from some point but if i give ending address till 20k it doesn't crash.i don't know why? so, if you know about these behavior then please let me know what i need to do.

**Comment by adamgreen** [comment]
@RajaniSureja I don't really understand what you are describing here. Can you show me your implementation of CrashCatcher_GetMemoryRegions() and better describe what isn't working as expected?
