### ISSUE TITLE
Dump without crash?

### ISSUE THREAD

**Issue by dstahlke** [adamgreen/CrashCatcher#6]
Thank you for this library.  Very useful.  I was able to get it working on an LPC4370.  But is there any way to produce a dump without inducing a fault?  Sometimes I'd like to just get a stack trace and let the program continue running.  I tried calling HardFault_Handler() directly and returning CRASH_CATCHER_EXIT from CrashCatcher_DumpEnd but this seems to just freeze.

**Comment by adamgreen** [comment]
You are correct, this scenario doesn’t currently work but it sounds like a good scenario to enable. 

I could see doing this through the handling of BKPT instructions when they are encountered in the instruction flow. This is something that I could look into enabling when I complete my current travels in a couple of days.

So I take it that your dump handlers are already to handle being called multiple times? For example, newer dumps won’t overwrite your older ones? How much memory are you dumping each time? If you aren’t using an RTOS with multiple stacks then maybe you would find it advantageous to only dump the current stack (mini dump) and not all of RAM?

**Comment by dstahlke** [comment]
I'm just dumping to UART using the HexDump.c routines.  My use case would be to initiate the dump from an interrupt handler when a certain character comes in from the UART.  Calling a function would work for me, as would a BKPT instruction.

I'm dumping all 282kB of ram, but at 2000000 baud it only takes a couple seconds.

This is bare metal (no RTOS).

**Comment by adamgreen** [comment]
I am working on this change and I hope to finish testing it tomorrow. Then I will push it up to GitHub for you to review. I took the BKPT approach since it causes an interrupt stack to be generated which reduces the amount of code that needed to be modified/added.

**Comment by adamgreen** [comment]
I pushed up a [new branch](https://github.com/adamgreen/CrashCatcher/tree/featureAddBKPTHandling) with my proposed change.

More information about the changes found in this branch can be found by reading the commit text for commit 6d99c3a.

@dstahlke Please let me know what you think.

**Comment by dstahlke** [comment]
Wow, that was fast!  And it works perfectly.  Thank you very much.  I wish I had started using this years ago.

**Comment by adamgreen** [comment]
@dstahlke I am happy to hear that it worked for you. I will merge into master once I finish a bit more testing.

**Comment by adamgreen** [comment]
@dstahlke Thanks again for raising this issue and testing the related change.

I finished my testing tonight and have merged this new functionality into master.
