### ISSUE TITLE
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

### ISSUE THREAD

**Issue by swordligit** [adamgreen/CrashCatcher#8]
I have ported the CrashCatcher, and I made some test,
after the fault, the CrashCather will dump the carsh log,
then I put this command:
```
 arm-none-eabi-gdb mytest.elf -ex "set target-charset ASCII" -ex "target remote | ./CrashDebug --elf mytest.elf --dump crash.txt"
```
The gdb start correctly and find the right crash postion, but
when I input "bt", it shows
```
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```
following is the log:
```
(gdb) bt
#0  app_event_callback (chan=0x2000f048 <channel_pool>, 
    ctx=0x20014300 <os_thread_def_stack_MyTestThread+4420>)
    at ../../services/mytest.cpp:1567
#1  0x0c0393e8 in test_callback (Chan=0x20012e70 <app_device>, 
    Info=0x20014300 <os_thread_def_stack_MyTestThread+4420>)
    at ../../services/test_api.cpp:831
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```
Is there any reason for the corrupt stack. but I think the stack is right,maybe
unwind is not correct. Because I only add the following test code:
```
    char *a = NULL;
    *a = 125;
    TRACE("a %d", *a);
```
which will cause a NULL pointer dereference error.

**Comment by adamgreen** [comment]
Other than that message, does that stack look corrupt to you? I don't know enough about your program to know for sure but that callstack looks like it might be valid to me and that message can just be ignored (as I usually do when debugging multithreaded RTOS apps with GDB.)

I think that is normal GDB behavior when unwinding a thread stack. Unlike main(), it doesn't know to stop unwinding when it hits the top of a RTOS thread stack. I think this would happen even if CrashCatcher/CrashDebug weren't in the picture (ie. using a JTAG debugger).

**Comment by adamgreen** [comment]
Please reopen if you still think that this problem is specific to CrashCatcher/CrashDebug.
